[package]
name = "ship-of-drools"
version = "1.1.0"
edition = "2021"

[[bin]]
name = "ship-of-drools"
path = "src/main.rs"

[dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
] }
